Remove coffee-script.
We started seeing the following error in production:

~/worldcubeassociation.org/WcaOnRails @production> tail -n 15 yarn-error.log
      decamelize "^1.0.0"
      window-size "0.1.0"

Trace:
  Error: https://registry.yarnpkg.com/coffee-script/-/coffee-script-1.12.8.tgz: Request failed "404 Not Found"
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:59296:26)
      at emitOne (events.js:115:13)
      at Request.emit (events.js:210:7)
      at Request.module.exports.Request.onRequestResponse (/usr/share/yarn/lib/cli.js:123897:10)
      at emitOne (events.js:115:13)
      at ClientRequest.emit (events.js:210:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:549:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
      at TLSSocket.socketOnData (_http_client.js:438:20)
      at emitOne (events.js:115:13)

It turns out that CoffeeScript on NPM has moved to "coffeescript" (no
hyphen). We aren't even using coffeescript, so I figured we might as
well remove it.